import "@/assets/styles/global.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
    title: "Create Next App",
    keywords: "next-js, nextJs",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Navbar/>
        <main>{children}</main>
        <Footer/>
        </body>
        </html>
    );
}
